name: "Install Violet"
description: "Installs LunarWatcher/violet in the workflow runner. Only compatible with Linux"

inputs:
  version:
    description: "What version to install. Mutually exclusive with 'latest'"
    required: false
    default: ''
  latest:
    description: "Whether to install the latest version. Mutually exclusive with 'version'"
    default: true
    required: false

runs:
  using: "composite"
  steps:
    - name: Yoink Violet artefact
      uses: robinraju/release-downloader@v1.12
      id: yoink-obsidian
      with:
        repository: LunarWatcher/violet
        latest: ${{ inputs.latest }}
        tarBall: false
        zipBall: false
        tag: ${{ inputs.version }}
        fileName: violet-linux-x86_64.tar.gz
        out-file-path: ${{ runner.temp }}/

    - name: Install violet artefact (Ubuntu)
      run: |
        # Required all of the sudden for some reason
        sudo apt-get upgrade libstdc++6
        sudo tar -xf ${{ runner.temp }}/violet-linux-x86_64.tar.gz -C /usr/local --strip-components=1
      shell: bash

    - name: Show violet
      run: |
        which violet
      shell: bash
